import streamlit as st
from orchestrator import AIOrchestrator
from database import add_task, get_user_profile

def problem_solver_page():
    st.subheader("🛠️ AI Workplace Problem Solver")
    st.caption("Diagnose enterprise operational roadblocks, analyze probable root causes, and execute step-by-step remediation runbooks.")

    username = st.session_state.get("username", "user")
    user_profile = get_user_profile(username)
    rag_engine = st.session_state.get("rag", None)

    # Preset Quick Problem Accelerators
    st.markdown("##### ⚡ Common Workplace Issue Accelerators:")
    col_p1, col_p2, col_p3 = st.columns(3)
    quick_problem = None
    if col_p1.button("🔌 Remote VPN Failed to Connect", use_container_width=True):
        quick_problem = "My remote VPN is failing to authenticate and the tunnel keeps dropping."
    if col_p2.button("🔒 Enterprise SSO Account Lockout", use_container_width=True):
        quick_problem = "My enterprise Single Sign-On account is locked out after repeated attempts."
    if col_p3.button("💳 Expense Reimbursement Rejection", use_container_width=True):
        quick_problem = "Why was my travel per-diem and flight reimbursement claim flagged or rejected?"

    custom_problem = st.text_input(
        "Describe workplace problem or system error:",
        value=quick_problem if quick_problem else "",
        placeholder="e.g., Cannot connect to clinical database or VPN handshake timed out..."
    )

    if st.button("🚀 Analyze & Generate Diagnostic Runbook", use_container_width=True, type="primary"):
        if custom_problem.strip():
            with st.spinner("Analyzing enterprise runbooks and executing diagnostic reasoning..."):
                diag_result = AIOrchestrator._execute_problem_solver(
                    query=custom_problem,
                    rag_engine=rag_engine,
                    user_profile=user_profile,
                    t_start=st.session_state.get("_start_time", 0)
                )
                st.session_state.latest_diagnostic = diag_result
        else:
            st.warning("Please provide a description of the workplace problem.")

    if "latest_diagnostic" in st.session_state and st.session_state.latest_diagnostic:
        diag = st.session_state.latest_diagnostic
        st.write("")
        st.markdown(diag["answer"])

        # Grounded Citations
        if diag.get("matches"):
            with st.expander(f"📚 Verified Knowledge Citations ({len(diag['matches'])} source references)", expanded=True):
                for idx, m in enumerate(diag["matches"], 1):
                    conf = int(min(m["score"] * 100, 99)) if m["score"] < 1.0 else 100
                    st.markdown(f"**Citation #{idx}** `Relevance: {conf}%` • *Chunk #{m.get('chunk_idx', 0) + 1}*")
                    st.markdown(f"> {m['chunk']}")

        st.divider()
        st.markdown("##### ⚡ Immediate Remediation Actions:")
        act_col1, act_col2, act_col3 = st.columns(3)

        with act_col1:
            if st.button("🎫 Escalate to Tier-2 Support Ticket", use_container_width=True):
                st.success("✅ Support Ticket `#INC-89421` dispatched to Operations Queue with diagnostic report attached.")
        with act_col2:
            if st.button("➕ Convert Steps to My Tasks", use_container_width=True):
                add_task(
                    username=username,
                    title=f"Resolve: {custom_problem[:35]}",
                    description="Execute 5-step diagnostic remediation steps generated by AI Problem Solver.",
                    priority="High",
                    source_doc="AI Problem Solver Runbook"
                )
                st.success("✅ Remediation checklist synchronized to **My Work** portal!")
        with act_col3:
            st.download_button(
                label="📥 Export Runbook (.md)",
                data=diag["answer"],
                file_name="diagnostic_remediation_runbook.md",
                mime="text/markdown",
                use_container_width=True
            )
